version: "3.9"
services:
  app:
    build: .
    environment:
      - REDIS_HOST=redis
    volumes:
      - .:/focus_yt
    image: dockerfile
    container_name: focusyt_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  
    ports:
      - 80:80
    depends_on:
      - app  
    



