version: "3.9"
services:
  app:
    build: .
    environment:
      - REDIS_HOST=redis
    volumes:
      - .:/focus_yt
    ports:
      - 8000:8000
    image: dockerfile
    container_name: focusyt_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    



