# Generated by Django 4.1.3 on 2023-08-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id_user',
            field=models.IntegerField(default=0),
        ),
    ]
