# Generated by Django 4.1.3 on 2023-08-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_alter_notes_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='videotitle',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
